package com.sjnewell;

// Workaround in case some of the setters aren't called
def propertyMissing(name) {
    null
}

// This should be called *first* after running tests.
//   src: the path to the src directory of the project
//   output: the file to store coverage results
def gather(src, output) {
    sh "lcov --capture -b \"${src}\" -d . --output-file \"${output}\" --no-external"
}

// This can be called after results have been gathered.  If there are files
// you don't care about they can be filtered from the report here.
//   input: a coverage report generated as the output of either gather or trim
//   output: the path to store the trimmed coverage report
//   pattern: the pattern to filter from the input report (*_test.cpp)
def trim(input, output, pattern) {
    sh "lcov -r ${input} \"${pattern}\" -o \"${output}\""
}

// This will a coverage report into a nice set of html pages.
//   input: a coverage report generated by either gather or trim
//   output: the output folder to store the coverage report
def process(input, output) {
    sh "genhtml \"${input}\" -o \"${output}\""
}
